# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-04 17:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinterest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='pinner',
        ),
    ]
