# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-04 18:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinterest', '0002_remove_board_pinner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pinner',
            name='avatar',
        ),
    ]
