# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-04 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinterest', '0003_remove_pinner_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='pinner',
            name='avatar',
            field=models.URLField(blank=True),
        ),
    ]
